{{- if and (not .Values.valkey.enabled) (not .Values.celery.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celery.fullname" . }}-broker
  labels:
    {{- include "celery.labels" . | nindent 4 }}
type: Opaque
stringData:
  broker-url: {{ .Values.celery.brokerUrl | quote }}
  result-backend: {{ .Values.celery.resultBackend | quote }}
{{- end }}
