apiVersion: v2
name: bookstack
description: BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information.
type: application
version: 2.4.1
appVersion: "25.12"
home: https://www.bookstackapp.com/
icon: https://media.githubusercontent.com/media/BookStackApp/website/master/static/images/logo.png
sources:
  - https://github.com/BookStackApp/BookStack
maintainers:
  - name: Tristan
    email: 5606292+drustan@users.noreply.github.com
annotations:
  artifacthub.io/category: web
  artifacthub.io/prerelease: "false"
dependencies:
  - name: mariadb
    version: "23.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: valkey
    version: "5.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
